EDITOR_BG = "#FFFFFF"
EDITOR_FONT_FAMILY = "Monaco"
EDITOR_FONT_SIZE = 11

LINE_NUMBER_BG = "#dcdcdc"
LINE_NUMBER_TEXT = "#000000"
CURRENT_LINE_BG = "#ffffd0"

STATUS_BAR_BG = "#f5f5f5"
STATUS_BAR_HEIGHT = 24

# Syntax highlighting colors
SYNTAX_KEYWORD = "#0000FF"
SYNTAX_STRING = "#A315AD"
SYNTAX_NUMBER = "#098658"
SYNTAX_COMMENT = "#008000"
SYNTAX_BUILTIN = "#795E26"
SYNTAX_DECORATOR = "#800000"
SYNTAX_CLASS_DEF = "#267F99"
SYNTAX_FUNCTION_DEF = "#267F99"

# Pair highlighting
PAIR_HIGHLIGHT = "#FFFD38"

# Welcome frame colors
WELCOME_TEXT_PRIMARY = "#000000"
WELCOME_TEXT_SECONDARY = "#888888"
WELCOME_DIVIDER = "#E0E0E0"

# Tab colors
TAB_STRIP_BG = "#FFFFFF"
TAB_SELECTED_BG = "#CEE6FC"
TAB_UNSELECTED_BG = "#FFFFFF"
TAB_BORDER = "#D2D2D2"
TAB_SELECTED_TEXT = "#2386FB"
TAB_UNSELECTED_TEXT = "#000000"
TAB_SELECTED_CLOSE_HOVER_BG = "#BBDCFB"
TAB_UNSELECTED_CLOSE_HOVER_BG = "#F0F0F0"
TAB_SEPARATOR = "#D2D2D2"
